config/routes.rb
Rails.application.routes.draw do
  resources :special_offers
  resources :menus
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "admin/dashboard#index"
  
  
  
  break if ARGV.join.include? 'assets:precompile'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/menu.rb
class Menu < ActiveRecord::Base
    belongs_to :special_offer
    
    #accepts_nested_attributes_for :special_offers, allow_destroy: true
end

app/models/special_offer.rb
class SpecialOffer < ActiveRecord::Base
  has_many :menus
  
  accepts_nested_attributes_for :menus, allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  #second change
  #before_filter :authenticate_user!
  
  protect_from_forgery with: :exception

end

app/controllers/menus_controller.rb
class MenusController < InheritedResources::Base

  private

    def menu_params
      params.require(:menu).permit(:name, :price)
    end
end

app/controllers/special_offers_controller.rb
class SpecialOffersController < InheritedResources::Base

  private

    def special_offer_params
      params.require(:special_offer).permit(:name, :price, :menu_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/special_offers_helper.rb
module SpecialOffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.price %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/special_offers/_form.html.erb
<%= form_for(@special_offer) do |f| %>
  <% if @special_offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@special_offer.errors.count, "error") %> prohibited this special_offer from being saved:</h2>

      <ul>
      <% @special_offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :menu_id %><br>
    <%= f.text_field :menu_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/special_offers/edit.html.erb
<h1>Editing Special Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @special_offer %> |
<%= link_to 'Back', special_offers_path %>

app/views/special_offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Special Offers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @special_offers.each do |special_offer| %>
      <tr>
        <td><%= special_offer.name %></td>
        <td><%= special_offer.price %></td>
        <td><%= special_offer.menu %></td>
        <td><%= link_to 'Show', special_offer %></td>
        <td><%= link_to 'Edit', edit_special_offer_path(special_offer) %></td>
        <td><%= link_to 'Destroy', special_offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Special offer', new_special_offer_path %>

app/views/special_offers/new.html.erb
<h1>New Special Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', special_offers_path %>

app/views/special_offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @special_offer.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @special_offer.price %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @special_offer.menu %>
</p>

<%= link_to 'Edit', edit_special_offer_path(@special_offer) %> |
<%= link_to 'Back', special_offers_path %>